fix(traverse): Image content w/ field_scale id
plone/plone.app.imaging pull request #42
Opened 2021-06-02 23:45 UTC by rpatterson

Adds a test that reproduces a bug in the edge case where a user creates a new content
instance of the `Image` type that happens to have a `context.id` that matches the same
`{field}_{scale}` format that is introspected by the image scale traverser to try and
reproduce a bug in that logic.

Also adds a fix for the bug.  I went with a conditional at the top of
`plone.app.imaging.traverse:ImageTraverser.publishTraverse` because I'm not sure of all
the implications of just calling `self.fallback(request, name)` first, otherwise I would
have gone with that as it seems like the correct behavior to me.  So LMK if someone who
knows better than I also thinks that's the right approach and I'll make the change.

Due to [an unrelated
bug](https://github.com/plone/Products.CMFPlone/issues/2200#issuecomment-843632261), I
wasn't able to get this test to reproduce the bug on the latest applicable Plone that
still supports Archetypes, version 5.2 under Python 2.7.  I found it easiest to develop
the test case and fix against the branch used in the latest `buildout.coredev` branch
where `ATContentTypes` was the default, namely `4.3`.  Once we're done making changes to
the test and fix I'll also forward port this commit to the `5.0-5.2` branches.

----

Corresponding PR for [an already reviewed and merged PR](https://github.com/plone/plone.app.imaging/pull/41#issuecomment-853434222).

2021-06-02 23:45 UTC, mister-roboto commented
@rpatterson thanks for creating this Pull Request and help improve Plone!

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass.

Whenever you feel that the pull request is ready to be tested, either start all jenkins jobs pull requests by yourself, or simply add a comment in this pull request stating:

```
@jenkins-plone-org please run jobs
```

With this simple comment all the jobs will be started automatically.

Happy hacking!

2021-06-02 23:45 UTC, rpatterson commented
@jenkins-plone-org please run jobs

2021-06-11 16:03 UTC, mauritsvanrees requested changes
LGTM.
But there is an error in the [Jenkins tests](https://jenkins.plone.org/job/pull-request-5.2-2.7/2032/testReport/junit/src.plone.app.imaging/tests/traversal_txt/) and it is in `plone.app.imaging`.

Note that the failing Python 3 test can be ignored, because plone.app.imaging is for Archetypes, so no Python 3 tests should be run.

2021-06-11 20:39 UTC, rpatterson commented
> But there is an error in the [Jenkins tests](https://jenkins.plone.org/job/pull-request-5.2-2.7/2032/testReport/junit/src.plone.app.imaging/tests/traversal_txt/) and it is in `plone.app.imaging`.

Thanks for catching that and sorry for not coming back and checking for myself.  It was a clean checkout issue with my `./src/plone/app/imaging/tests/tmp/.gitignore` usage that resulted in false positives for me locally.  I was able to reproduce the issue, confirmed a fix and force pushed that.  I'm waiting to confirm that the CI now passes.

@jenkins-plone-org please run jobs@jenkins-plone-org please run jobs

Unfortunately, it looks like the same underlying issue is in effect in my corresponding PRs on the other branches.  I'm a little confused as to why *those* didn't also fail in the same way.  At any rate, I'm looking into those so expect follow-up PRs from me for those other branches.

2021-06-12 10:50 UTC, mauritsvanrees approved these changes

2021-06-12 10:54 UTC, mauritsvanrees commented
The 2.7 tests pass now, except for one totally unrelated failure that I will ignore. I will merge.

Only the master branch is tested on Jenkins because it is used in 5.2. So these are the first tests that actually run. For the other branches, Jenkins is irrelevant, and you should just try to run the tests locally.

2021-06-12 10:54 UTC, merged

2021-06-15 09:39 UTC, mauritsvanrees commented
I have released 2.1.2 with this fix. Thanks!